import imag_Qrcode from "./imag_Qrcode"
import diretriz from "./diretrizes"
import objetivo from "./objetivo"
import pontosPositivos from "./pontosPositivos" 
import faq from "./faq"
import membros from "./membros"
import estatuto_cpa from "./estatuto_cpa"
import pilar_iesEsinaes from "./pilar_iesEsinaes"
import resultado from "./resultado"
import satisfacao_biopark from "./satisfacao_biopark"
import satisfacao_curso from "./satisfacao_curso"
import satisfacao_infra from "./satisfacao_infra"
import membrosDestaque from "./membroDestaque"

export const schemaTypes = [imag_Qrcode, diretriz, objetivo, pontosPositivos, faq, pilar_iesEsinaes, membros,membrosDestaque,estatuto_cpa, resultado, satisfacao_biopark, satisfacao_curso, satisfacao_infra]
